

spring.application.name=ETF-CONSUMIDOR
server.port=8081

spring.datasource.url=jdbc:oracle:thin:@etvtuimca831glgtbz_high?TNS_ADMIN=/app/wallet
spring.datasource.username=ADMIN
spring.datasource.password=Backend12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.rabbitmq.addresses=${RABBITMQ_ADDRESSES}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}